version: 2.0
jobs:
  build:
    working_directory: ~/kuneiform
    docker:
      - image: quay.io/haskell_works/stack-build-cabal:2018-01-29

    steps:
      - checkout
      - run: grep '^resolver:' stack.yaml > resolver.txt

      - restore_cache:
          keys:
            - emga7ct-dot-stack-{{ checksum "stack.yaml" }}-{{ checksum "kuneiform.cabal" }}
            - emga7ct-dot-stack-{{ checksum "stack.yaml" }}
            - emga7ct-dot-stack-{{ checksum "resolver.txt" }}
            - emga7ct-dot-stack-resolver-{{ checksum "resolver.txt" }}
      - run: stack setup
      - save_cache:
          key: emga7ct-dot-stack-resolver-{{ checksum "resolver.txt" }}
          paths:
            - ~/.stack
      - save_cache:
          key: emga7ct-dot-stack-setup-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack

      - run:
          command: stack build --test --no-run-tests --dependencies-only -j4
          no_output_timeout: 1200
      - save_cache:
          key: emga7ct-dot-stack-{{ checksum "resolver.txt" }}
          paths:
            - ~/.stack

      - restore_cache:
          key: stack-work-{{ checksum "stack.yaml" }}
      - run: stack build --test --no-run-tests
      - save_cache:
          key: emga7ct-dot-stack-{{ checksum "stack.yaml" }}-{{ checksum "kuneiform.cabal" }}
          paths:
            - ~/.stack
      - save_cache:
          key: stack-work-{{ checksum "stack.yaml" }}
          paths: ~/kuneiform/.stack-work

      - run:
          name: Running unit tests
          command: stack test

      - deploy:
          command: |
            if [ "$CIRCLE_PROJECT_USERNAME" == "haskell-works" ]; then
              if [[ "$CIRCLE_BRANCH" == master ]]; then
                when tag autotag
              elif [[ "$CIRCLE_TAG" =~ v.* ]]; then
                publish
              fi
            fi

deployment:
  tagged_builds:
    tag: /v.*/
    commands:
      - echo "Make tags run in 2.0"
