name:                kuneiform
version:             0.1.0.1
github:              "githubuser/kuneiform"
license:             BSD3
author:              "John Ky"
maintainer:          "newhoggy@gmail.com"
copyright:           "2018 John Ky"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/kuneiform#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- amazonka
- amazonka-core
- amazonka-dynamodb
- amazonka-dynamodb-streams
- amazonka-kinesis
- amazonka-s3
- amazonka-sns
- amazonka-sqs
- async
- async-pool
- base-prelude
- brick
- bytestring
- containers
- conduit
- conduit-combinators
- dependent-sum
- fast-logger
- hourglass
- http-client
- hw-conduit
- lens
- microlens
- monad-logger
- optparse-applicative
- reflex
- singletons
- stm
- stm-containers
- text
- vector
- vty

library:
  source-dirs: src

executables:
  kuneiform:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
     - gitrev
     - kuneiform

tests:
  kuneiform-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kuneiform
    - hedgehog
    - hspec
    - hw-hedgehog
    - hw-hspec-hedgehog
