name:                kuneiform
version:             0.1.0.0
github:              "githubuser/kuneiform"
license:             BSD3
author:              "John Ky"
maintainer:          "newhoggy@gmail.com"
copyright:           "2018 John Ky"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/kuneiform#readme>

dependencies:
- base >= 4.7 && < 5
- BoundedChan
- aeson
- amazonka
- amazonka-core
- amazonka-dynamodb
- amazonka-dynamodb-streams
- amazonka-kinesis
- amazonka-s3
- amazonka-sns
- amazonka-sqs
- async
- async-pool
- brick
- bytestring
- conduit
- conduit-combinators
- fast-logger
- http-client
- hw-conduit
- lens
- microlens
- monad-logger
- optparse-applicative
- singletons
- text
- vector
- vty

library:
  source-dirs: src

executables:
  kuneiform-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
     - gitrev
     - kuneiform

tests:
  kuneiform-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kuneiform
    - hspec
