resolver: lts-12.14

packages:
- '.'

flags: {}

extra-package-dbs: []

extra-deps:
  - git: git@github.com:brendanhay/amazonka
    commit: 248f7b2a7248222cc21cef6194cd1872ba99ac5d
    subdirs:
      - amazonka
